// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_uc89WTbUrC-H5qHiMygUjzWEiNvWLjw',
    appId: '1:941580715785:web:25c2b62e5fb2ba4e3b75d8',
    messagingSenderId: '941580715785',
    projectId: 'vpg-notification',
    authDomain: 'vpg-notification.firebaseapp.com',
    storageBucket: 'vpg-notification.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5rXupHOn19GQ0RIB56hNEZWpf_94PNyM',
    appId: '1:941580715785:android:8b0471e4d54fe8d43b75d8',
    messagingSenderId: '941580715785',
    projectId: 'vpg-notification',
    storageBucket: 'vpg-notification.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDk4l9_yP_bsRrFv0G8c_kT3VIFs9Fh5XU',
    appId: '1:941580715785:ios:8e333a316a73c5d73b75d8',
    messagingSenderId: '941580715785',
    projectId: 'vpg-notification',
    storageBucket: 'vpg-notification.firebasestorage.app',
    iosBundleId: 'com.example.escort',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDk4l9_yP_bsRrFv0G8c_kT3VIFs9Fh5XU',
    appId: '1:941580715785:ios:8e333a316a73c5d73b75d8',
    messagingSenderId: '941580715785',
    projectId: 'vpg-notification',
    storageBucket: 'vpg-notification.firebasestorage.app',
    iosBundleId: 'com.example.escort',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_uc89WTbUrC-H5qHiMygUjzWEiNvWLjw',
    appId: '1:941580715785:web:6cbe02e1be7186d03b75d8',
    messagingSenderId: '941580715785',
    projectId: 'vpg-notification',
    authDomain: 'vpg-notification.firebaseapp.com',
    storageBucket: 'vpg-notification.firebasestorage.app',
  );
}
