"""messages model added sendertype as PK

Revision ID: 05096958f50c
Revises: b8aea2ed3f7b
Create Date: 2025-10-31 14:55:54.742411

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '05096958f50c'
down_revision = 'b8aea2ed3f7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sender_type', sa.String(length=20), nullable=False))
        batch_op.alter_column('sender_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.create_index('idx_message_conversation', ['conversation_id', 'created_at'], unique=False)
        batch_op.create_index('idx_message_sender', ['conversation_id', 'sender_id', 'sender_type'], unique=False)
        batch_op.drop_constraint(batch_op.f('messages_ibfk_3'), type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('messages_ibfk_3'), 'users', ['sender_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_index('idx_message_sender')
        batch_op.drop_index('idx_message_conversation')
        batch_op.alter_column('sender_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.drop_column('sender_type')

    # ### end Alembic commands ###
