"""Subscription status,checks & reminders

Revision ID: 13ced6775356
Revises: 776fadc6f3c5
Create Date: 2025-11-09 14:20:26.964585

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '13ced6775356'
down_revision = '776fadc6f3c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pending_payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('checkout_id'))
        batch_op.drop_index(batch_op.f('payment_reference'))

    op.drop_table('pending_payments')
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('renewal_day', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('reminder_7days_sent', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('reminder_3days_sent', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('last_reminder_sent', sa.TIMESTAMP(), nullable=True))
        batch_op.add_column(sa.Column('cancelled_at', sa.TIMESTAMP(), nullable=True))
        batch_op.add_column(sa.Column('cancellation_reason', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_column('cancellation_reason')
        batch_op.drop_column('cancelled_at')
        batch_op.drop_column('last_reminder_sent')
        batch_op.drop_column('reminder_3days_sent')
        batch_op.drop_column('reminder_7days_sent')
        batch_op.drop_column('renewal_day')

    op.create_table('pending_payments',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('checkout_id', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('checkout_url', mysql.TEXT(), nullable=True),
    sa.Column('payment_reference', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('plan_id', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('amount', mysql.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('currency', mysql.VARCHAR(length=3), nullable=False),
    sa.Column('status', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('expires_at', mysql.TIMESTAMP(), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', mysql.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['advertisers.id'], name=op.f('pending_payments_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('pending_payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('payment_reference'), ['payment_reference'], unique=True)
        batch_op.create_index(batch_op.f('checkout_id'), ['checkout_id'], unique=True)

    # ### end Alembic commands ###
