"""Added to_dict to user settings model

Revision ID: 25c00a1d8724
Revises: 8131032bda82
Create Date: 2025-08-18 14:53:45.977968

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '25c00a1d8724'
down_revision = '8131032bda82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.alter_column('notification_enabled',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
        batch_op.alter_column('dark_mode_enabled',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
        batch_op.alter_column('show_online_status',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
        batch_op.alter_column('read_receipts',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
        batch_op.alter_column('selected_language',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=10),
               nullable=False)
        batch_op.alter_column('selected_theme',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=False)
        batch_op.create_unique_constraint(None, ['user_id'])
        batch_op.drop_constraint(batch_op.f('user_settings_ibfk_1'), type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('user_settings_ibfk_1'), 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('selected_theme',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('selected_language',
               existing_type=sa.String(length=10),
               type_=mysql.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('read_receipts',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
        batch_op.alter_column('show_online_status',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
        batch_op.alter_column('dark_mode_enabled',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
        batch_op.alter_column('notification_enabled',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)

    # ### end Alembic commands ###
