"""Second migration

Revision ID: 3f2a35b2a2ec
Revises: 642f55639978
Create Date: 2025-07-16 23:50:27.653806

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3f2a35b2a2ec'
down_revision = '642f55639978'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_tokens',
    sa.Column('id', sa.NullType(), nullable=False),
    sa.Column('user_id', sa.NullType(), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=False),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comments',
    sa.Column('id', sa.NullType(), nullable=False),
    sa.Column('user_id', sa.NullType(), nullable=False),
    sa.Column('target_type', sa.Enum('post', 'profile', name='comment_target_type'), nullable=False),
    sa.Column('target_id', sa.NullType(), nullable=False),
    sa.Column('parent_comment_id', sa.NullType(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('likes_count', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['parent_comment_id'], ['comments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conversations',
    sa.Column('id', sa.NullType(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=True),
    sa.Column('user_id', sa.NullType(), nullable=False),
    sa.Column('last_message_id', sa.NullType(), nullable=True),
    sa.Column('last_message_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('posts',
    sa.Column('id', sa.NullType(), nullable=False),
    sa.Column('user_id', sa.NullType(), nullable=False),
    sa.Column('image_id', sa.Text(), nullable=True),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subscriptions',
    sa.Column('id', sa.NullType(), nullable=False),
    sa.Column('user_id', sa.NullType(), nullable=False),
    sa.Column('amount_paid', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('payment_method', sa.String(length=20), nullable=True),
    sa.Column('start_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('end_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_blocks',
    sa.Column('id', sa.NullType(), nullable=False),
    sa.Column('blocker_id', sa.NullType(), nullable=False),
    sa.Column('blocked_id', sa.NullType(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['blocked_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['blocker_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('blocker_id', 'blocked_id', name='uq_blocker_blocked')
    )
    op.create_table('user_settings',
    sa.Column('id', sa.NullType(), nullable=False),
    sa.Column('user_id', sa.NullType(), nullable=False),
    sa.Column('notification_enabled', sa.Boolean(), nullable=True),
    sa.Column('dark_mode_enabled', sa.Boolean(), nullable=True),
    sa.Column('show_online_status', sa.Boolean(), nullable=True),
    sa.Column('read_receipts', sa.Boolean(), nullable=True),
    sa.Column('selected_language', sa.String(length=20), nullable=True),
    sa.Column('selected_theme', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comment_likes',
    sa.Column('id', sa.NullType(), nullable=False),
    sa.Column('comment_id', sa.NullType(), nullable=False),
    sa.Column('user_id', sa.NullType(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('comment_id', 'user_id', name='uq_comment_user')
    )
    op.create_table('messages',
    sa.Column('id', sa.NullType(), nullable=False),
    sa.Column('conversation_id', sa.NullType(), nullable=False),
    sa.Column('sender_id', sa.NullType(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('advertisers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('phone_number', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('profile_image_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('is_online', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('password_hash', sa.String(length=100), nullable=True))
        batch_op.drop_index(batch_op.f('idx_advertiser_active'))
        batch_op.create_index('idx_advertiser_active', ['last_active'], unique=False)
        batch_op.create_index('idx_advertiser_bio', ['bio'], unique=False)
        batch_op.create_index('idx_advertiser_online', ['is_online'], unique=False)
        batch_op.create_index('idx_advertiser_password', ['password_hash'], unique=False)
        batch_op.create_unique_constraint(None, ['username'])
        batch_op.drop_column('number')
        batch_op.drop_column('passwords_hash')
        batch_op.drop_column('is_active')
        batch_op.drop_column('profile_picture')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=255), nullable=False))
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=255),
               nullable=False)
        batch_op.alter_column('phone_number',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.String(length=20),
               nullable=False)
        batch_op.alter_column('location',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=255),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('updated_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('password_hash',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('email'))
        batch_op.create_index('idx_advertiser_password', ['password_hash'], unique=False)
        batch_op.create_index('idx_user_active', ['last_active'], unique=False)
        batch_op.create_index('idx_user_email', ['email'], unique=False)
        batch_op.create_index('idx_user_gender', ['gender'], unique=False)
        batch_op.create_index('idx_user_location', ['location'], unique=False)
        batch_op.create_index('idx_user_name', ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_name'), ['name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_name'))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index('idx_user_name')
        batch_op.drop_index('idx_user_location')
        batch_op.drop_index('idx_user_gender')
        batch_op.drop_index('idx_user_email')
        batch_op.drop_index('idx_user_active')
        batch_op.drop_index('idx_advertiser_password')
        batch_op.create_index(batch_op.f('email'), ['email'], unique=True)
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('location',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('phone_number',
               existing_type=sa.String(length=20),
               type_=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.drop_column('name')

    with op.batch_alter_table('advertisers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_picture', mysql.VARCHAR(length=500), nullable=True))
        batch_op.add_column(sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('passwords_hash', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('number', mysql.VARCHAR(length=20), nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_index('idx_advertiser_password')
        batch_op.drop_index('idx_advertiser_online')
        batch_op.drop_index('idx_advertiser_bio')
        batch_op.drop_index('idx_advertiser_active')
        batch_op.create_index(batch_op.f('idx_advertiser_active'), ['is_active'], unique=False)
        batch_op.drop_column('password_hash')
        batch_op.drop_column('is_online')
        batch_op.drop_column('profile_image_url')
        batch_op.drop_column('phone_number')
        batch_op.drop_column('username')

    op.drop_table('messages')
    op.drop_table('comment_likes')
    op.drop_table('user_settings')
    op.drop_table('user_blocks')
    op.drop_table('subscriptions')
    op.drop_table('posts')
    op.drop_table('conversations')
    op.drop_table('comments')
    op.drop_table('auth_tokens')
    # ### end Alembic commands ###
