"""Changed auth access tokens String

Revision ID: 574465e51b28
Revises: b021a3e1d47f
Create Date: 2025-08-03 20:15:26.801690

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '574465e51b28'
down_revision = 'b021a3e1d47f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auth_tokens', schema=None) as batch_op:
        batch_op.alter_column('access_token',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=512),
               nullable=True)
        batch_op.alter_column('refresh_token',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=512),
               nullable=True)
        batch_op.create_index('idx_auth_token_access', ['access_token'], unique=False)
        batch_op.create_index('idx_auth_token_expires', ['expires_at'], unique=False)
        batch_op.create_index('idx_auth_token_refresh', ['refresh_token'], unique=False)
        batch_op.create_index('idx_auth_token_user', ['user_id', 'user_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_auth_tokens_access_token'), ['access_token'], unique=False)
        batch_op.drop_constraint(batch_op.f('auth_tokens_ibfk_1'), type_='foreignkey')
        batch_op.drop_column('ip_address')
        batch_op.drop_column('user_agent')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.drop_index(batch_op.f('idx_advertiser_password'))
        batch_op.create_index('idx_user_password', ['password_hash'], unique=False)
        batch_op.drop_column('profile_picture')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_picture', mysql.VARCHAR(length=255), nullable=True))
        batch_op.drop_index('idx_user_password')
        batch_op.create_index(batch_op.f('idx_advertiser_password'), ['password_hash'], unique=False)
        batch_op.drop_column('is_active')

    with op.batch_alter_table('auth_tokens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_agent', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('ip_address', mysql.TEXT(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('auth_tokens_ibfk_1'), 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_index(batch_op.f('ix_auth_tokens_access_token'))
        batch_op.drop_index('idx_auth_token_user')
        batch_op.drop_index('idx_auth_token_refresh')
        batch_op.drop_index('idx_auth_token_expires')
        batch_op.drop_index('idx_auth_token_access')
        batch_op.alter_column('refresh_token',
               existing_type=sa.String(length=512),
               type_=mysql.TEXT(),
               nullable=False)
        batch_op.alter_column('access_token',
               existing_type=sa.String(length=512),
               type_=mysql.TEXT(),
               nullable=False)

    # ### end Alembic commands ###
