"""intial migration

Revision ID: 642f55639978
Revises: 
Create Date: 2025-07-15 23:46:29.805662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '642f55639978'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('advertisers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('number', sa.String(length=20), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('gender', sa.Enum('male', 'female', 'other', name='advertiser_gender_enum'), nullable=False),
    sa.Column('profile_picture', sa.String(length=500), nullable=True),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('business_type', sa.String(length=100), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('advertisers', schema=None) as batch_op:
        batch_op.create_index('idx_advertiser_active', ['is_active'], unique=False)
        batch_op.create_index('idx_advertiser_business_type', ['business_type'], unique=False)
        batch_op.create_index('idx_advertiser_email', ['email'], unique=False)
        batch_op.create_index('idx_advertiser_gender', ['gender'], unique=False)
        batch_op.create_index('idx_advertiser_location', ['location'], unique=False)
        batch_op.create_index('idx_advertiser_name', ['name'], unique=False)
        batch_op.create_index('idx_advertiser_verified', ['is_verified'], unique=False)
        batch_op.create_index(batch_op.f('ix_advertisers_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_advertisers_name'), ['name'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('number', sa.String(length=20), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('gender', sa.Enum('male', 'female', 'other', name='gender_enum'), nullable=False),
    sa.Column('profile_picture', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('idx_user_active', ['is_active'], unique=False)
        batch_op.create_index('idx_user_email', ['email'], unique=False)
        batch_op.create_index('idx_user_gender', ['gender'], unique=False)
        batch_op.create_index('idx_user_location', ['location'], unique=False)
        batch_op.create_index('idx_user_name', ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_name'), ['name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_name'))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index('idx_user_name')
        batch_op.drop_index('idx_user_location')
        batch_op.drop_index('idx_user_gender')
        batch_op.drop_index('idx_user_email')
        batch_op.drop_index('idx_user_active')

    op.drop_table('users')
    with op.batch_alter_table('advertisers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_advertisers_name'))
        batch_op.drop_index(batch_op.f('ix_advertisers_email'))
        batch_op.drop_index('idx_advertiser_verified')
        batch_op.drop_index('idx_advertiser_name')
        batch_op.drop_index('idx_advertiser_location')
        batch_op.drop_index('idx_advertiser_gender')
        batch_op.drop_index('idx_advertiser_email')
        batch_op.drop_index('idx_advertiser_business_type')
        batch_op.drop_index('idx_advertiser_active')

    op.drop_table('advertisers')
    # ### end Alembic commands ###
