"""Future changes

Revision ID: 729eac5ad3fa
Revises: 7ebefad44ccc
Create Date: 2025-07-27 23:54:37.349159

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '729eac5ad3fa'
down_revision = '7ebefad44ccc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('advertisers', schema=None) as batch_op:
        batch_op.create_index('idx_advertiser_online', ['is_online'], unique=False)
        batch_op.create_index('idx_advertiser_password', ['password_hash'], unique=False)
        batch_op.create_unique_constraint(None, ['username'])
        batch_op.drop_column('profile_picture')
        batch_op.drop_column('number')
        batch_op.drop_column('business_type')
        batch_op.drop_column('is_active')
        batch_op.drop_column('company_name')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('phone_number', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('last_active', sa.TIMESTAMP(), nullable=True))
        batch_op.add_column(sa.Column('password_hash', sa.String(length=100), nullable=True))
        batch_op.drop_index(batch_op.f('idx_user_active'))
        batch_op.create_index('idx_user_active', ['last_active'], unique=False)
        batch_op.create_index('idx_advertiser_password', ['password_hash'], unique=False)
        batch_op.create_unique_constraint(None, ['username'])
        batch_op.drop_column('is_active')
        batch_op.drop_column('profile_picture')
        batch_op.drop_column('number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('number', mysql.VARCHAR(length=20), nullable=False))
        batch_op.add_column(sa.Column('profile_picture', mysql.VARCHAR(length=500), nullable=True))
        batch_op.add_column(sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_index('idx_advertiser_password')
        batch_op.drop_index('idx_user_active')
        batch_op.create_index(batch_op.f('idx_user_active'), ['is_active'], unique=False)
        batch_op.drop_column('password_hash')
        batch_op.drop_column('last_active')
        batch_op.drop_column('phone_number')
        batch_op.drop_column('username')

    with op.batch_alter_table('advertisers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_name', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('business_type', mysql.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('number', mysql.VARCHAR(length=20), nullable=False))
        batch_op.add_column(sa.Column('profile_picture', mysql.VARCHAR(length=500), nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_index('idx_advertiser_password')
        batch_op.drop_index('idx_advertiser_online')

    # ### end Alembic commands ###
