"""Changed user & advertiser models

Revision ID: 73db21c57337
Revises: dffebf1826da
Create Date: 2025-08-03 20:11:55.253719

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '73db21c57337'
down_revision = 'dffebf1826da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('advertisers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    with op.batch_alter_table('auth_tokens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_type', sa.Enum('user', 'advertiser', name='user_type_enum'), nullable=False))
        batch_op.create_index('idx_auth_token_access', ['access_token'], unique=False)
        batch_op.create_index('idx_auth_token_expires', ['expires_at'], unique=False)
        batch_op.create_index('idx_auth_token_refresh', ['refresh_token'], unique=False)
        batch_op.create_index('idx_auth_token_user', ['user_id', 'user_type'], unique=False)
        batch_op.drop_constraint(batch_op.f('auth_tokens_ibfk_1'), type_='foreignkey')
        batch_op.drop_column('ip_address')
        batch_op.drop_column('user_agent')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.drop_index(batch_op.f('idx_advertiser_password'))
        batch_op.create_index('idx_user_password', ['password_hash'], unique=False)
        batch_op.drop_column('profile_picture')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_picture', mysql.VARCHAR(length=255), nullable=True))
        batch_op.drop_index('idx_user_password')
        batch_op.create_index(batch_op.f('idx_advertiser_password'), ['password_hash'], unique=False)
        batch_op.drop_column('is_active')

    with op.batch_alter_table('auth_tokens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_agent', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('ip_address', mysql.TEXT(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('auth_tokens_ibfk_1'), 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_index('idx_auth_token_user')
        batch_op.drop_index('idx_auth_token_refresh')
        batch_op.drop_index('idx_auth_token_expires')
        batch_op.drop_index('idx_auth_token_access')
        batch_op.drop_column('user_type')

    with op.batch_alter_table('advertisers', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
