"""Added media handlers for messaging

Revision ID: 776fadc6f3c5
Revises: 9f4c5bd9d593
Create Date: 2025-11-08 18:09:24.768116

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '776fadc6f3c5'
down_revision = '9f4c5bd9d593'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('advertisers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_advertisers_fcm_token'))
        batch_op.drop_column('fcm_token_updated_at')
        batch_op.drop_column('fcm_token')

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message_type', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('media_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('thumbnail_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('media_metadata', sa.JSON(), nullable=True))
        batch_op.create_index('idx_message_type', ['message_type'], unique=False)
        batch_op.drop_constraint(batch_op.f('messages_ibfk_2'), type_='foreignkey')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_users_fcm_token'))
        batch_op.drop_column('fcm_token_updated_at')
        batch_op.drop_column('fcm_token')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fcm_token', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('fcm_token_updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True))
        batch_op.create_index(batch_op.f('idx_users_fcm_token'), ['fcm_token'], unique=False)

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('messages_ibfk_2'), 'users', ['sender_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_index('idx_message_type')
        batch_op.drop_column('media_metadata')
        batch_op.drop_column('thumbnail_url')
        batch_op.drop_column('media_url')
        batch_op.drop_column('message_type')

    with op.batch_alter_table('advertisers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fcm_token', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('fcm_token_updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True))
        batch_op.create_index(batch_op.f('idx_advertisers_fcm_token'), ['fcm_token'], unique=False)

    # ### end Alembic commands ###
