"""Future changes

Revision ID: 7ebefad44ccc
Revises: 3f2a35b2a2ec
Create Date: 2025-07-27 23:50:55.340086

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7ebefad44ccc'
down_revision = '3f2a35b2a2ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('target_type', sa.Enum('post', 'profile', name='comment_target_type'), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('parent_comment_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('likes_count', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['parent_comment_id'], ['comments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('last_message_id', sa.Integer(), nullable=True),
    sa.Column('last_message_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('image_id', sa.Text(), nullable=True),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount_paid', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('payment_method', sa.String(length=20), nullable=True),
    sa.Column('start_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('end_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_blocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('blocker_id', sa.Integer(), nullable=False),
    sa.Column('blocked_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['blocked_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['blocker_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('blocker_id', 'blocked_id', name='uq_blocker_blocked')
    )
    op.create_table('user_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('notification_enabled', sa.Boolean(), nullable=True),
    sa.Column('dark_mode_enabled', sa.Boolean(), nullable=True),
    sa.Column('show_online_status', sa.Boolean(), nullable=True),
    sa.Column('read_receipts', sa.Boolean(), nullable=True),
    sa.Column('selected_language', sa.String(length=20), nullable=True),
    sa.Column('selected_theme', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comment_likes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('comment_id', 'user_id', name='uq_comment_user')
    )
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('advertisers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('phone_number', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('profile_image_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('is_online', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('last_active', sa.TIMESTAMP(), nullable=True))
        batch_op.add_column(sa.Column('bio', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('password_hash', sa.String(length=100), nullable=True))
        batch_op.drop_index(batch_op.f('idx_advertiser_business_type'))
        batch_op.drop_index(batch_op.f('idx_advertiser_active'))
        batch_op.create_index('idx_advertiser_active', ['last_active'], unique=False)
        batch_op.create_index('idx_advertiser_bio', ['bio'], unique=False)
        batch_op.create_index('idx_advertiser_online', ['is_online'], unique=False)
        batch_op.create_index('idx_advertiser_password', ['password_hash'], unique=False)
        batch_op.create_unique_constraint(None, ['username'])
        batch_op.drop_column('profile_picture')
        batch_op.drop_column('is_active')
        batch_op.drop_column('business_type')
        batch_op.drop_column('number')
        batch_op.drop_column('company_name')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('phone_number', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('last_active', sa.TIMESTAMP(), nullable=True))
        batch_op.add_column(sa.Column('password_hash', sa.String(length=100), nullable=True))
        batch_op.drop_index(batch_op.f('idx_user_active'))
        batch_op.create_index('idx_user_active', ['last_active'], unique=False)
        batch_op.create_index('idx_advertiser_password', ['password_hash'], unique=False)
        batch_op.create_unique_constraint(None, ['username'])
        batch_op.drop_column('profile_picture')
        batch_op.drop_column('number')
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('number', mysql.VARCHAR(length=20), nullable=False))
        batch_op.add_column(sa.Column('profile_picture', mysql.VARCHAR(length=500), nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_index('idx_advertiser_password')
        batch_op.drop_index('idx_user_active')
        batch_op.create_index(batch_op.f('idx_user_active'), ['is_active'], unique=False)
        batch_op.drop_column('password_hash')
        batch_op.drop_column('last_active')
        batch_op.drop_column('phone_number')
        batch_op.drop_column('username')

    with op.batch_alter_table('advertisers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_name', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('number', mysql.VARCHAR(length=20), nullable=False))
        batch_op.add_column(sa.Column('business_type', mysql.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('profile_picture', mysql.VARCHAR(length=500), nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_index('idx_advertiser_password')
        batch_op.drop_index('idx_advertiser_online')
        batch_op.drop_index('idx_advertiser_bio')
        batch_op.drop_index('idx_advertiser_active')
        batch_op.create_index(batch_op.f('idx_advertiser_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('idx_advertiser_business_type'), ['business_type'], unique=False)
        batch_op.drop_column('password_hash')
        batch_op.drop_column('bio')
        batch_op.drop_column('last_active')
        batch_op.drop_column('is_online')
        batch_op.drop_column('profile_image_url')
        batch_op.drop_column('phone_number')
        batch_op.drop_column('username')

    op.drop_table('messages')
    op.drop_table('comment_likes')
    op.drop_table('user_settings')
    op.drop_table('user_blocks')
    op.drop_table('subscriptions')
    op.drop_table('posts')
    op.drop_table('conversations')
    op.drop_table('comments')
    # ### end Alembic commands ###
