"""Change imag id to image url

Revision ID: 8131032bda82
Revises: 574465e51b28
Create Date: 2025-08-15 21:35:51.947399

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8131032bda82'
down_revision = '574465e51b28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.Text(), nullable=True))
        batch_op.drop_column('image_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_id', mysql.TEXT(), nullable=True))
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
