"""Changed FK in posts from user to advertisers

Revision ID: 8ce18bbd85fb
Revises: fdfa5859a7c2
Create Date: 2025-07-31 19:52:29.972398

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8ce18bbd85fb'
down_revision = 'fdfa5859a7c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('advertiser_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('posts_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'advertisers', ['advertiser_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('posts_ibfk_1'), 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('advertiser_id')

    # ### end Alembic commands ###
