"""fix_sender_id_nullable_with_sender_type

Revision ID: 9f4c5bd9d593
Revises: 05096958f50c
Create Date: 2025-10-31 15:05:07.428454

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9f4c5bd9d593'
down_revision = '05096958f50c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index('idx_message_conversation', ['conversation_id', 'created_at'], unique=False)
        batch_op.create_index('idx_message_sender', ['conversation_id', 'sender_id', 'sender_type'], unique=False)
        batch_op.drop_constraint(batch_op.f('messages_ibfk_3'), type_='foreignkey')

    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invoice_id', sa.String(length=100), nullable=True))
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=mysql.TIMESTAMP(),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('subscriptions_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'advertisers', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('subscriptions_ibfk_1'), 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('updated_at',
               existing_type=mysql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               nullable=True)
        batch_op.drop_column('invoice_id')

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('messages_ibfk_3'), 'users', ['sender_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_index('idx_message_sender')
        batch_op.drop_index('idx_message_conversation')

    # ### end Alembic commands ###
