"""Upgraded subscription & payment

Revision ID: b1371a848ee4
Revises: 6e33472cec63
Create Date: 2025-09-18 20:22:01.040351

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b1371a848ee4'
down_revision = '6e33472cec63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pending_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('checkout_id', sa.String(length=100), nullable=False),
    sa.Column('checkout_url', sa.Text(), nullable=False),
    sa.Column('payment_reference', sa.String(length=100), nullable=False),
    sa.Column('plan_id', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('expires_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('checkout_id'),
    sa.UniqueConstraint('payment_reference')
    )
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plan_id', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('plan_name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('currency', sa.String(length=3), nullable=False))
        batch_op.add_column(sa.Column('checkout_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('payment_reference', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('intasend_tracking_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('payment_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('auto_renew', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('next_billing_date', sa.TIMESTAMP(), nullable=True))
        batch_op.alter_column('amount_paid',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=False)
        batch_op.alter_column('payment_method',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('start_date',
               existing_type=mysql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('end_date',
               existing_type=mysql.TIMESTAMP(),
               nullable=False)
        batch_op.create_unique_constraint(None, ['payment_reference'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('end_date',
               existing_type=mysql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('start_date',
               existing_type=mysql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('payment_method',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('amount_paid',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=True)
        batch_op.drop_column('next_billing_date')
        batch_op.drop_column('auto_renew')
        batch_op.drop_column('payment_status')
        batch_op.drop_column('intasend_tracking_id')
        batch_op.drop_column('payment_reference')
        batch_op.drop_column('checkout_id')
        batch_op.drop_column('currency')
        batch_op.drop_column('plan_name')
        batch_op.drop_column('plan_id')

    op.drop_table('pending_payments')
    # ### end Alembic commands ###
