"""Subscription&Pending models updated

Revision ID: b8aea2ed3f7b
Revises: 2fd972c1eb96
Create Date: 2025-10-24 00:52:23.991032

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b8aea2ed3f7b'
down_revision = '2fd972c1eb96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pending_payments', schema=None) as batch_op:
        batch_op.alter_column('checkout_url',
               existing_type=mysql.TEXT(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=mysql.TIMESTAMP(),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('pending_payments_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'advertisers', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invoice_id', sa.String(length=100), nullable=True))
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=mysql.TIMESTAMP(),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('subscriptions_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'advertisers', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_constraint('subscriptions_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('subscriptions_ibfk_1'), 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('updated_at',
               existing_type=mysql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               nullable=True)
        batch_op.drop_column('invoice_id')

    with op.batch_alter_table('pending_payments', schema=None) as batch_op:
        batch_op.drop_constraint('subscriptions_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('pending_payments_ibfk_1'), 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('updated_at',
               existing_type=mysql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('checkout_url',
               existing_type=mysql.TEXT(),
               nullable=False)

    # ### end Alembic commands ###
