<<<<<<<< HEAD:server/migrations/versions/74f977a10aaf_sean.py
"""Sean

Revision ID: 74f977a10aaf
Revises: 
Create Date: 2025-07-31 00:15:41.590787
========
"""Initial migration

Revision ID: f7fd78021320
Revises: 
Create Date: 2025-07-31 00:04:31.048094
>>>>>>>> master:server/migrations/versions/f7fd78021320_initial_migration.py

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
<<<<<<<< HEAD:server/migrations/versions/74f977a10aaf_sean.py
revision = '74f977a10aaf'
========
revision = 'f7fd78021320'
>>>>>>>> master:server/migrations/versions/f7fd78021320_initial_migration.py
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('advertisers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('gender', sa.Enum('Male', 'Female', 'other', name='advertiser_gender_enum'), nullable=False),
    sa.Column('profile_image_url', sa.String(length=500), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('is_online', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_active', sa.TIMESTAMP(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('password_hash', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    with op.batch_alter_table('advertisers', schema=None) as batch_op:
        batch_op.create_index('idx_advertiser_active', ['last_active'], unique=False)
        batch_op.create_index('idx_advertiser_email', ['email'], unique=False)
        batch_op.create_index('idx_advertiser_gender', ['gender'], unique=False)
        batch_op.create_index('idx_advertiser_location', ['location'], unique=False)
        batch_op.create_index('idx_advertiser_name', ['name'], unique=False)
        batch_op.create_index('idx_advertiser_online', ['is_online'], unique=False)
        batch_op.create_index('idx_advertiser_password', ['password_hash'], unique=False)
        batch_op.create_index('idx_advertiser_verified', ['is_verified'], unique=False)
        batch_op.create_index(batch_op.f('ix_advertisers_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_advertisers_name'), ['name'], unique=False)

<<<<<<<< HEAD:server/migrations/versions/74f977a10aaf_sean.py
========
    op.create_table('conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('last_message_id', sa.Integer(), nullable=True),
    sa.Column('last_message_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['last_message_id'], ['messages.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
>>>>>>>> master:server/migrations/versions/f7fd78021320_initial_migration.py
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('gender', sa.Enum('Male', 'Female', 'other', name='advertiser_gender_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_active', sa.TIMESTAMP(), nullable=True),
<<<<<<<< HEAD:server/migrations/versions/74f977a10aaf_sean.py
    sa.Column('password_hash', sa.String(length=100), nullable=True),
========
    sa.Column('password_hash', sa.String(length=256), nullable=True),
>>>>>>>> master:server/migrations/versions/f7fd78021320_initial_migration.py
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('idx_advertiser_password', ['password_hash'], unique=False)
        batch_op.create_index('idx_user_active', ['last_active'], unique=False)
        batch_op.create_index('idx_user_email', ['email'], unique=False)
        batch_op.create_index('idx_user_gender', ['gender'], unique=False)
        batch_op.create_index('idx_user_location', ['location'], unique=False)
        batch_op.create_index('idx_user_name', ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_name'), ['name'], unique=False)

    op.create_table('auth_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=False),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('target_type', sa.Enum('post', 'profile', name='comment_target_type'), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('parent_comment_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('likes_count', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['parent_comment_id'], ['comments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('image_id', sa.Text(), nullable=True),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount_paid', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('payment_method', sa.String(length=20), nullable=True),
    sa.Column('start_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('end_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_blocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('blocker_id', sa.Integer(), nullable=False),
    sa.Column('blocked_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['blocked_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['blocker_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('blocker_id', 'blocked_id', name='uq_blocker_blocked')
    )
    op.create_table('user_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('notification_enabled', sa.Boolean(), nullable=True),
    sa.Column('dark_mode_enabled', sa.Boolean(), nullable=True),
    sa.Column('show_online_status', sa.Boolean(), nullable=True),
    sa.Column('read_receipts', sa.Boolean(), nullable=True),
    sa.Column('selected_language', sa.String(length=20), nullable=True),
    sa.Column('selected_theme', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comment_likes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('comment_id', 'user_id', name='uq_comment_user')
    )
<<<<<<<< HEAD:server/migrations/versions/74f977a10aaf_sean.py
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
========
>>>>>>>> master:server/migrations/versions/f7fd78021320_initial_migration.py
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
<<<<<<<< HEAD:server/migrations/versions/74f977a10aaf_sean.py
    op.drop_table('messages')
========
>>>>>>>> master:server/migrations/versions/f7fd78021320_initial_migration.py
    op.drop_table('comment_likes')
    op.drop_table('user_settings')
    op.drop_table('user_blocks')
    op.drop_table('subscriptions')
    op.drop_table('posts')
<<<<<<<< HEAD:server/migrations/versions/74f977a10aaf_sean.py
    op.drop_table('conversations')
========
>>>>>>>> master:server/migrations/versions/f7fd78021320_initial_migration.py
    op.drop_table('comments')
    op.drop_table('auth_tokens')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_name'))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index('idx_user_name')
        batch_op.drop_index('idx_user_location')
        batch_op.drop_index('idx_user_gender')
        batch_op.drop_index('idx_user_email')
        batch_op.drop_index('idx_user_active')
        batch_op.drop_index('idx_advertiser_password')

    op.drop_table('users')
<<<<<<<< HEAD:server/migrations/versions/74f977a10aaf_sean.py
========
    op.drop_table('messages')
    op.drop_table('conversations')
>>>>>>>> master:server/migrations/versions/f7fd78021320_initial_migration.py
    with op.batch_alter_table('advertisers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_advertisers_name'))
        batch_op.drop_index(batch_op.f('ix_advertisers_email'))
        batch_op.drop_index('idx_advertiser_verified')
        batch_op.drop_index('idx_advertiser_password')
        batch_op.drop_index('idx_advertiser_online')
        batch_op.drop_index('idx_advertiser_name')
        batch_op.drop_index('idx_advertiser_location')
        batch_op.drop_index('idx_advertiser_gender')
        batch_op.drop_index('idx_advertiser_email')
        batch_op.drop_index('idx_advertiser_active')

    op.drop_table('advertisers')
    # ### end Alembic commands ###
